/**
 * c05: Context Compression 示例代码
 *
 * 最小化的上下文压缩系统实现
 * 基于 Claude Code 源码分析
 */

// ============================================
// 1. 类型定义
// ============================================

interface Message {
  role: 'user' | 'assistant' | 'system'
  content: string | any[]
}

interface TokenWarningState {
  percentLeft: number
  isAboveWarningThreshold: boolean
  isAboveErrorThreshold: boolean
  isAboveAutoCompactThreshold: boolean
}

interface CompactBoundaryMessage extends Message {
  role: 'system'
  type: 'compact_boundary'
  content: string
  originalMessages: Message[]
  tokenStats: {
    before: number
    after: number
    saved: number
  }
}

// ============================================
// 2. Token 计数器
// ============================================

/**
 * 简化的 Token 计数器
 * 实际应使用 tiktoken 库
 */
function countTokens(messages: Message[]): number {
  let total = 0
  for (const msg of messages) {
    const content = typeof msg.content === 'string'
      ? msg.content
      : JSON.stringify(msg.content)
    // 简化计算: ~4 字符 = 1 token
    total += Math.ceil(content.length / 4)
  }
  return total
}

// ============================================
// 3. 阈值检查器
// ============================================

class ThresholdChecker {
  private readonly maxTokens: number
  private readonly bufferTokens: number
  private readonly maxOutputTokens: number

  constructor(maxContextWindow: number = 200_000) {
    this.maxOutputTokens = 20_000
    this.bufferTokens = 13_000
    this.maxTokens = maxContextWindow
  }

  getAutoCompactThreshold(): number {
    return this.maxTokens - this.maxOutputTokens - this.bufferTokens
  }

  getWarningThreshold(): number {
    return this.getAutoCompactThreshold() + 20_000
  }

  getErrorThreshold(): number {
    return this.maxTokens - 10_000
  }

  check(currentTokens: number): TokenWarningState {
    const percentLeft = ((this.maxTokens - currentTokens) / this.maxTokens) * 100

    return {
      percentLeft,
      isAboveWarningThreshold: currentTokens > this.getWarningThreshold(),
      isAboveErrorThreshold: currentTokens > this.getErrorThreshold(),
      isAboveAutoCompactThreshold: currentTokens > this.getAutoCompactThreshold(),
    }
  }
}

// ============================================
// 4. 上下文分析器
// ============================================

interface ContextAnalysis {
  totalTokens: number
  messageCount: number
  toolUseCount: number
  userMessageCount: number
  assistantMessageCount: number
}

function analyzeContext(messages: Message[]): ContextAnalysis {
  let toolUseCount = 0
  let userMessageCount = 0
  let assistantMessageCount = 0

  for (const msg of messages) {
    if (msg.role === 'user') userMessageCount++
    if (msg.role === 'assistant') assistantMessageCount++

    // 检查工具调用
    if (Array.isArray(msg.content)) {
      toolUseCount += msg.content.filter(
        (block: any) => block.type === 'tool_use'
      ).length
    }
  }

  return {
    totalTokens: countTokens(messages),
    messageCount: messages.length,
    toolUseCount,
    userMessageCount,
    assistantMessageCount,
  }
}

// ============================================
// 5. 摘要生成器 (模拟)
// ============================================

interface SummaryGenerator {
  generate(messages: Message[]): Promise<string>
}

class MockSummaryGenerator implements SummaryGenerator {
  async generate(messages: Message[]): Promise<string> {
    // 实际应调用 LLM API 生成摘要
    const analysis = analyzeContext(messages)

    // 模拟摘要生成
    const summary = `[Context Summary]
- Total messages: ${analysis.messageCount}
- Tool calls: ${analysis.toolUseCount}
- User messages: ${analysis.userMessageCount}
- Assistant messages: ${analysis.assistantMessageCount}

Key points from the conversation:
- (This is a mock summary)
- In production, this would be generated by an LLM
`

    return summary
  }
}

// ============================================
// 6. 压缩器
// ============================================

interface CompactConfig {
  keepRecent: number      // 保留最近 N 条消息
  minMessagesToCompact: number  // 最少多少条消息才压缩
}

const DEFAULT_COMPACT_CONFIG: CompactConfig = {
  keepRecent: 5,
  minMessagesToCompact: 10,
}

class Compactor {
  private summaryGenerator: SummaryGenerator
  private config: CompactConfig

  constructor(
    summaryGenerator: SummaryGenerator,
    config: CompactConfig = DEFAULT_COMPACT_CONFIG
  ) {
    this.summaryGenerator = summaryGenerator
    this.config = config
  }

  async compact(messages: Message[]): Promise<{
    messages: Message[]
    boundary: CompactBoundaryMessage | null
    stats: { before: number; after: number; saved: number } | null
  }> {
    // 消息太少不压缩
    if (messages.length < this.config.minMessagesToCompact) {
      return { messages, boundary: null, stats: null }
    }

    const beforeTokens = countTokens(messages)

    // 分割消息
    const toCompact = messages.slice(0, -this.config.keepRecent)
    const toKeep = messages.slice(-this.config.keepRecent)

    // 生成摘要
    const summary = await this.summaryGenerator.generate(toCompact)

    // 创建边界消息
    const boundary: CompactBoundaryMessage = {
      role: 'system',
      type: 'compact_boundary',
      content: summary,
      originalMessages: toCompact,
      tokenStats: {
        before: beforeTokens,
        after: countTokens([{ role: 'system', content: summary }]),
        saved: 0, // 稍后计算
      },
    }

    boundary.tokenStats.saved =
      boundary.tokenStats.before - boundary.tokenStats.after

    // 组合新消息
    const newMessages: Message[] = [boundary, ...toKeep]

    return {
      messages: newMessages,
      boundary,
      stats: boundary.tokenStats,
    }
  }
}

// ============================================
// 7. 自动压缩管理器
// ============================================

class AutoCompactManager {
  private checker: ThresholdChecker
  private compactor: Compactor
  private consecutiveFailures: number = 0
  private maxConsecutiveFailures: number = 3

  constructor(checker: ThresholdChecker, compactor: Compactor) {
    this.checker = checker
    this.compactor = compactor
  }

  async checkAndCompact(messages: Message[]): Promise<{
    compacted: boolean
    messages: Message[]
    stats?: { before: number; after: number; saved: number }
  }> {
    const tokens = countTokens(messages)
    const state = this.checker.check(tokens)

    if (!state.isAboveAutoCompactThreshold) {
      return { compacted: false, messages }
    }

    // 检查连续失败
    if (this.consecutiveFailures >= this.maxConsecutiveFailures) {
      console.log('[AutoCompact] Skipped due to consecutive failures')
      return { compacted: false, messages }
    }

    try {
      console.log('[AutoCompact] Starting compression...')
      const result = await this.compactor.compact(messages)

      if (result.boundary) {
        this.consecutiveFailures = 0
        console.log(`[AutoCompact] Saved ${result.stats!.saved} tokens`)
        return { compacted: true, messages: result.messages, stats: result.stats! }
      }

      return { compacted: false, messages }
    } catch (error) {
      this.consecutiveFailures++
      console.error(`[AutoCompact] Failed (${this.consecutiveFailures} times)`)
      return { compacted: false, messages }
    }
  }
}

// ============================================
// 8. 演示
// ============================================

async function main() {
  console.log('=== Context Compression Demo ===\n')

  // 初始化组件
  const checker = new ThresholdChecker(200_000)
  const summaryGenerator = new MockSummaryGenerator()
  const compactor = new Compactor(summaryGenerator)
  const autoCompactManager = new AutoCompactManager(checker, compactor)

  // 创建模拟消息
  const messages: Message[] = []

  // 添加一些消息
  for (let i = 0; i < 20; i++) {
    messages.push({
      role: i % 2 === 0 ? 'user' : 'assistant',
      content: `Message ${i}: This is a sample message with some content to simulate a real conversation. `.repeat(50),
    })
  }

  console.log(`Initial messages: ${messages.length}`)
  console.log(`Initial tokens: ${countTokens(messages).toLocaleString()}`)

  // 检查阈值
  const state = checker.check(countTokens(messages))
  console.log(`\nThreshold check:`)
  console.log(`  Percent left: ${state.percentLeft.toFixed(1)}%`)
  console.log(`  Above warning: ${state.isAboveWarningThreshold}`)
  console.log(`  Above auto-compact: ${state.isAboveAutoCompactThreshold}`)

  // 添加更多消息触发压缩
  console.log('\n--- Adding more messages to trigger auto-compact ---')
  for (let i = 0; i < 200; i++) {
    messages.push({
      role: i % 2 === 0 ? 'user' : 'assistant',
      content: `Large message ${i}: `.repeat(100) + 'x'.repeat(500),
    })
  }

  console.log(`\nAfter adding: ${messages.length} messages, ${countTokens(messages).toLocaleString()} tokens`)

  // 执行自动压缩
  const result = await autoCompactManager.checkAndCompact(messages)

  console.log(`\nCompact result:`)
  console.log(`  Compacted: ${result.compacted}`)
  if (result.stats) {
    console.log(`  Before: ${result.stats.before.toLocaleString()} tokens`)
    console.log(`  After: ${result.stats.after.toLocaleString()} tokens`)
    console.log(`  Saved: ${result.stats.saved.toLocaleString()} tokens (${((result.stats.saved / result.stats.before) * 100).toFixed(1)}%)`)
  }
  console.log(`  Messages: ${result.messages.length}`)

  // 手动压缩演示
  console.log('\n--- Manual compact demo ---')
  const manualResult = await compactor.compact(messages)
  if (manualResult.boundary) {
    console.log('Boundary message preview:')
    console.log(manualResult.boundary.content.substring(0, 200) + '...')
  }
}

main().catch(console.error)